env:
  global:
    - SWIFT_VERSION=4.2
    - REPOSITORY_URL=https://github.com/matthewfaller/algorithm-practice.git

sudo: required
language: generic
os: linux
dist: trusty
services:
  - docker

script: docker run swift:$SWIFT_VERSION /bin/bash -c "git clone $REPOSITORY_URL && cd algorithm-practice && git checkout $TRAVIS_COMMIT && swift test" 

# {
#   "os": "linux",
#   "dist": "trusty",
#   "sudo": "required",
#   "group": "stable",
#   "language": "bash",
#   "services": [
#     "docker"
#   ]
# }
# language: swift
# script: swift test

  #.travis.yml