sudo: required
language: bash
os: trusty
services:
  - docker

script: docker run swift /bin/bash -c "git clone https://github.com/matthewfaller/algorithm-practice.git && cd algorithm-practice && swift test" 

# {
#   "os": "linux",
#   "dist": "trusty",
#   "sudo": "required",
#   "group": "stable",
#   "language": "bash",
#   "services": [
#     "docker"
#   ]
# }
# language: swift
# script: swift test

  #.travis.yml